keys:
  - &1password age187zlwuajhnq3f3j4f3jxe7sgndpslrw7acuwxe42h93qp7gaegpqdmlccp
  - &fadeoutz age1yrl4dtlwefhgfrardfwyyj6g6csxzt2yl86hg3q6492cqwg5j3lsjgll8w
  - &unmusique age1qjsa6xq4lercw4jxm5afhc8apwzdsnumqpv5u3a5wy6c0ec9kfmqvqrh34
  - &zephyr age1wjtpgteqny7schmrzpsqcja6luxescntl42etrk2sy25zy6snyjs5cy5y7
creation_rules:
  - path_regex: users/.*/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
      - *unmusique
      - *zephyr
  - path_regex: machines/fadeoutz/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
