keys:
  - &1password age187zlwuajhnq3f3j4f3jxe7sgndpslrw7acuwxe42h93qp7gaegpqdmlccp
  - &fadeoutz age1yrl4dtlwefhgfrardfwyyj6g6csxzt2yl86hg3q6492cqwg5j3lsjgll8w
  - &unmusique age1erh5uqmskp79psdkvz6u5fgtxlul3g08uemktllu0syg6lsrjyfsvla0f5
  - &silver-chariot age14kme0qdc89dkmpj558lz3run9y77zjm26awfvfhhzaval06jm4js45qc2g
  - &sisterhood age1x6z9tjpx8t39wr7pusxv70yheefy3uk63levgrr24gfr70pln5ys8f43ep
  - &golden-experience age14vqfexzssjx4hae8t3ee2zk5fu2wpwrlvtpnsqfsyv8lu3cq43zqpg3mxq
  - &ghostholding age15qf22v35zxffq8lh0a0wtppr20p99ayhj7u7clxzywwne54yzu8qnykh8s
  - &dreamflasher age19yfzje6pm8382xnzy6xj456c3753rvym0p2mp7jztsf62rjc83wskrdqpk
creation_rules:
  - path_regex: users/.*/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
      - *unmusique
      - *silver-chariot
      - *sisterhood
      - *golden-experience
      - *ghostholding
      - *dreamflasher
  - path_regex: machines/fadeoutz/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
  - path_regex: machines/nixos/sisterhood/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *sisterhood
  - path_regex: machines/nixos/unmusique/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *unmusique
  - path_regex: machines/nixos/silver-chariot/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *silver-chariot
