keys:
  - &1password age187zlwuajhnq3f3j4f3jxe7sgndpslrw7acuwxe42h93qp7gaegpqdmlccp
  - &fadeoutz age1yrl4dtlwefhgfrardfwyyj6g6csxzt2yl86hg3q6492cqwg5j3lsjgll8w
  - &unmusique age12764pwy5lyt7d3fxj2m2ysd26j77k4st09dm6w095t7zwrhhtsdsd7c542
creation_rules:
  - path_regex: users/.*/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
      - *unmusique
  - path_regex: machines/fadeoutz/secrets/.*$
    key_groups:
    - age:
      - *1password
      - *fadeoutz
