{
  pkgs,
  config,
  ...
}:
{
  imports = [
    ./network.nix
    ./disk-config.nix
  ];

  config = {
    rv32ima.machine.enable = true;
    rv32ima.machine.hostName = "ghostholding";
    rv32ima.machine.stateVersion = "25.05";
    rv32ima.machine.platform = "x86_64-linux";
    rv32ima.machine.users = [
      "root"
    ];
    rv32ima.machine.isRemote = true;
    rv32ima.machine.impermanence.enable = true;

    services.getty.autologinUser = "root";

    boot.initrd.availableKernelModules = [
      "ahci"
      "xhci_pci"
      "megaraid_sas"
      "usbhid"
      "usb_storage"
      "sd_mod"
      "sr_mod"
    ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [
      "kvm-intel"
      "mlxfw"
    ];
    boot.kernelParams = [
      "console=tty0"
      "console=ttyS0,115200"
      "net.ifnames=0"
      "biosdevname=0"
    ];
    boot.kernelPatches = [
      {
        name = "mlx-stuff";
        patch = null;
        extraConfig = ''
          MELLANOX_PLATFORM y
          MLXREG_HOTPLUG m
          MLXREG_IO m
          MLXREG_LC m
          NVSW_SN2201 m
          SENSORS_MLXREG_FAN m
        '';
      }
    ];
    boot.blacklistedKernelModules = [
      "i2c_mux_reg"
    ];

    hardware.enableAllFirmware = true;
    hardware.fancontrol.enable = true;
    hardware.fancontrol.config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon4=devices/pci0000:00/0000:00:01.2/0000:03:00.0
      DEVNAME=hwmon4=mlxsw
      FCTEMPS=hwmon4/pwm1=hwmon4/temp1_input
      FCFANS= hwmon4/pwm1=
      MINTEMP=hwmon4/pwm1=40
      MAXTEMP=hwmon4/pwm1=80
      MINSTART=hwmon4/pwm1=50
      MINSTOP=hwmon4/pwm1=50
      MINPWM=hwmon4/pwm1=0
    '';

    networking.hostId = "35a29483";

    services.udev.extraRules = ''
      SUBSYSTEM=="net", ACTION=="add", DRIVERS=="mlxsw_spectrum*", NAME="sw$attr{phys_port_name}"
    '';

    boot.kernel.sysctl = {
      "net.ipv4.ip_forward" = "1";
      "net.ipv6.conf.all.forwarding" = "1";
      "net.ipv6.conf.default.forwarding" = "1";
      "net.ipv6.conf.all.keep_addr_on_down" = "1";
      "net.ipv6.conf.default.keep_addr_on_down" = "1";
      "net.ipv4.conf.all.ignore_routes_with_linkdown" = "1";
      "net.ipv6.conf.all.ignore_routes_with_linkdown" = "1";
      "net.ipv4.conf.default.ignore_routes_with_linkdown" = "1";
      "net.ipv6.conf.default.ignore_routes_with_linkdown" = "1";
      "net.ipv4.fib_multipath_hash_policy" = "1";
      "net.ipv6.fib_multipath_hash_policy" = "1";
      "net.ipv6.conf.all.ndisc_notify" = "1";
      "net.ipv6.conf.default.ndisc_notify" = "1";
      "net.ipv4.conf.all.rp_filter" = "0";
      "net.ipv4.conf.default.rp_filter" = "0";
      "net.ipv4.ip_forward_update_priority" = "0";
      "net.ipv6.route.skip_notify_on_dev_down" = "1";
      "net.ipv4.fib_multipath_use_neigh" = "1";
      "net.ipv6.route.max_size" = "16384";
      "net.ipv4.neigh.default.gc_thresh2" = "8192";
      "net.ipv6.neigh.default.gc_thresh2" = "8192";
      "net.ipv4.neigh.default.gc_thresh3" = "8192";
      "net.ipv6.neigh.default.gc_thresh3" = "8192";
    };

    services.frr.config = ''
      frr defaults traditional
      log syslog informational
      ipv6 forwarding
      service integrated-vtysh-config
      router bgp 395388
      bgp router-id 199.255.18.181
      bgp ebgp-requires-policy
      bgp default dynamic-capability
      neighbor cofractal peer-group
      neighbor cofractal remote-as 26073
      neighbor 2606:7940:32:3c::2 peer-group cofractal
      neighbor 2606:7940:32:3c::3 peer-group cofractal
      !
      address-family ipv4 unicast
        redistribute connected
        neighbor cofractal activate
        neighbor cofractal send-nexthop-characteristics
        neighbor cofractal capability extended-nexthop
        neighbor cofractal route-map IMPORT in
        neighbor cofractal route-map EXPORT out
      exit-address-family
      !
      address-family ipv6
        redistribute connected
        neighbor cofractal activate
        neighbor cofractal route-map IMPORT in
        neighbor cofractal route-map EXPORT out
      exit-address-family
      !
      route-map EXPORT deny 100
      !
      route-map EXPORT permit 1
      match interface lo
      set ipv6 next-hop global 2606:7940:32:3c::11
      !
      route-map IMPORT deny 1
      !
      line vty
      !
    '';
    services.frr.bgpd.enable = true;

    services.tailscale.enable = true;
    services.tailscale.openFirewall = false;
    services.tailscale.interfaceName = "userspace-networking";

    services.openssh.enable = true;
    services.openssh.openFirewall = true;

    programs.fish.enable = true;
    programs.fish.useBabelfish = true;
  };
}
