#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[aliases]
check = [
    "util",
    "exec",
    "--",
    "bash",
    "-c",
    "jj diff -r \"${1:-ancestors(@) ~ ancestors(trunk())}\" --name-only --no-pager | xargs prek run --files",
]
fetch = ["git", "fetch"]
init = ["git", "init", "--colocate"]
push = ["git", "push"]
speedway = ["util", "exec", "--", "fish", "-c", "speedway"]
jj = []
pr = ["util", "exec", "jj-pr"]
rt = ["rebase", "-d", "trunk()"]
track = ["bookmark", "track"]
tug = [
    "bookmark",
    "move",
    "--from",
    "heads(::@- & bookmarks())",
    "--to",
    "@-",
]

[fix.tools.keep-sorted]
command = ["keep-sorted", "-"]
enabled = true
patterns = ["glob:'**/*'"]

[fix.tools.terraform-fmt]
command = ["terraform", "fmt", "-"]
enabled = true
patterns = ["glob:'**/*.tf'"]

[fix.tools.treefmt]
command = ["treefmt", "--stdin"]
enabled = true
patterns = ["glob:**/*"]

[remotes.origin]
auto-track-bookmarks = "glob:'eford/*' & glob:'ellie/*'"

[revset-aliases]
T = "trunk()"
"why_immutable(r)" = "(r & immutable()) | roots(r:: & immutable_heads())"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[ui]
merge-editor = "diffconflicts"
