services:
    grafana:
        client_secret: ENC[AES256_GCM,data:LhqPwyntz19CVNc/r9DfU516Vn5qCgUEcrmgnTtmNA7Q2X6tbWyB/pJjEfVzjmLpQuIMSdr9+PglrOVh8PSFoA==,iv:ZVP8/AQF+Enr7r8OaI7Rzu53423fIhjFoWZHjsTDkiw=,tag:saO4DnOZG/URJBtDyqzvcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETXdML2ZqZHZ1Q1Z5N2Jy
            ODhOeGpIcFUyRnFMOUptVHU4dnBRdVNvaHk4CldoUzJwL0dxcFk0ejZwdXRjUjhR
            ZEJhOVFQYW1mcmNyeGZ6c1ZheHhDK28KLS0tIG1OcTNaZXFrRzJQcG9SUkt4Lys5
            SlNNNThwUWd1am9YL2tCaEtUcFNDSjgKJsxkc65VnDQltu1UtakJBcB3h2uPYOQo
            lFks+DZqapb8mtxXa0OV1kE+/L2Yp+kvGNbIOsBCOYZQ5VSFdTf9OQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age187zlwuajhnq3f3j4f3jxe7sgndpslrw7acuwxe42h93qp7gaegpqdmlccp
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVMycW55cnJUNEUyeXpa
            ZDI4OXpreWJMZVpyTDJUTmJudEhmSXpNQ1Q0CkY3aE1UcUw1YVRTK1NxeEtMMUZO
            RTBTOEk1UnFOaURULzZwZ3hCNEhsS28KLS0tIEE1V2M4WWRhNlV3M1o0b0FXMGhw
            QnlyTkZnRXRDZlNOZ1VwL2JjWm93VXcKgbsIxUJiEDP/2X9XW7US3ZqakxaXf/A2
            vzXpmYd+4yti3Nt8iKMgHfteT0R3UDTu92G35b+Jz6RMrNu7GNL1qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1erh5uqmskp79psdkvz6u5fgtxlul3g08uemktllu0syg6lsrjyfsvla0f5
    lastmodified: "2026-06-19T22:11:36Z"
    mac: ENC[AES256_GCM,data:voyxerSefSqE/7jtOSKGSGT1H6AxKoukbPLDHm/vA9iSxtTD6Y9yc8bwoCE57IXILzXqUtt47pmm5vw6klWYsh4aYzjbhXPdjUMVbebEZMenLzAmjTSQNvQEN8qmIpDhinZE4AWqfoPYCYJvltRgq4QreLOcm8WLeM+5mKvRsxw=,iv:Ak8Z4hDHJSp9ghpqXhgF4wm4w6E+9ds2jam3PhGgjjE=,tag:CS/zgzlz5MNI0gmb6j2/ew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
